In [66]:
import pandas as pd

In [67]:
s = pd.Series([120, 340, 210], index=["Kochi", "Bengaluru", "Chennai"])
print(s)

Kochi        120
Bengaluru    340
Chennai      210
dtype: int64

In [68]:
s.loc["Kochi":"Chennai"]

Kochi        120
Bengaluru    340
Chennai      210
dtype: int64

In [69]:
print(s["Bengaluru"])

340

In [70]:
s["Kochi":"Bengaluru"]

Kochi        120
Bengaluru    340
dtype: int64

In [71]:
s  = pd.Series([120, 340, 210], index=["Kochi", "Bengaluru", "Chennai"])
s2 = pd.Series([1, 2, 3],       index=["Chennai", "Kochi", "Bengaluru"])
print(s + s2)

Bengaluru    343
Chennai      211
Kochi        122
dtype: int64

In [72]:
s3 = pd.Series([5, 6], index=["Kochi", "Mumbai"])

In [73]:
print(s+s3)

Bengaluru      NaN
Chennai        NaN
Kochi        125.0
Mumbai         NaN
dtype: float64

In [74]:
df = pd.read_table(r"C:\Users\vatta\OneDrive\Desktop\Projects\Python\Datasets\countries of the world.csv", delimiter = ',')
df

             Country                               Region
0       Afghanistan         ASIA (EX. NEAR EAST)
1           Albania   EASTERN EUROPE
2           Algeria   NORTHERN AFRICA
3    American Samoa   OCEANIA
4           Andorra   WESTERN EUROPE
..               ...                                  ...
222       West Bank   NEAR EAST
223  Western Sahara   NORTHERN AFRICA
224           Yemen   NEAR EAST
225          Zambia   SUB-SAHARAN AFRICA
226        Zimbabwe   SUB-SAHARAN AFRICA

[227 rows x 2 columns]

In [75]:
#To display all the rows
#pd.set_option('display.max.rows',235)

In [76]:
df

             Country                               Region
0       Afghanistan         ASIA (EX. NEAR EAST)
1           Albania   EASTERN EUROPE
2           Algeria   NORTHERN AFRICA
3    American Samoa   OCEANIA
4           Andorra   WESTERN EUROPE
..               ...                                  ...
222       West Bank   NEAR EAST
223  Western Sahara   NORTHERN AFRICA
224           Yemen   NEAR EAST
225          Zambia   SUB-SAHARAN AFRICA
226        Zimbabwe   SUB-SAHARAN AFRICA

[227 rows x 2 columns]

In [77]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 227 entries, 0 to 226
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  227 non-null    str
 1   Region   227 non-null    str
dtypes: str(2)
memory usage: 3.7 KB

In [78]:
df.shape

(227, 2)

In [79]:
df.head(5)

           Country                               Region
0     Afghanistan         ASIA (EX. NEAR EAST)
1         Albania   EASTERN EUROPE
2         Algeria   NORTHERN AFRICA
3  American Samoa   OCEANIA
4         Andorra   WESTERN EUROPE

In [80]:
df.tail(10)

                Country                               Region
217            Vanuatu   OCEANIA
218          Venezuela               LATIN AMER. & CARIB
219            Vietnam         ASIA (EX. NEAR EAST)
220     Virgin Islands               LATIN AMER. & CARIB
221  Wallis and Futuna   OCEANIA
222          West Bank   NEAR EAST
223     Western Sahara   NORTHERN AFRICA
224              Yemen   NEAR EAST
225             Zambia   SUB-SAHARAN AFRICA
226           Zimbabwe   SUB-SAHARAN AFRICA

In [81]:
df.loc[224]

Country                                 Yemen
Region     NEAR EAST
Name: 224, dtype: str

In [82]:
df.iloc[224]

Country                                 Yemen
Region     NEAR EAST
Name: 224, dtype: str

In [83]:
df[df['Country'].str.contains('United')]

                   Country                               Region
212  United Arab Emirates   NEAR EAST
213        United Kingdom   WESTERN EUROPE
214         United States   NORTHERN AMERICA

In [84]:
df2 = df.set_index('Country')
df2

                                              Region
Country
Afghanistan            ASIA (EX. NEAR EAST)
Albania          EASTERN EUROPE
Algeria          NORTHERN AFRICA
American Samoa   OCEANIA
Andorra          WESTERN EUROPE
...                                              ...
West Bank        NEAR EAST
Western Sahara   NORTHERN AFRICA
Yemen            NEAR EAST
Zambia           SUB-SAHARAN AFRICA
Zimbabwe         SUB-SAHARAN AFRICA

[227 rows x 1 columns]

In [85]:
df2.filter(like='United',axis=0)

                                                    Region
Country
United Arab Emirates   NEAR EAST
United Kingdom         WESTERN EUROPE
United States          NORTHERN AMERICA

In [86]:
df2

                                              Region
Country
Afghanistan            ASIA (EX. NEAR EAST)
Albania          EASTERN EUROPE
Algeria          NORTHERN AFRICA
American Samoa   OCEANIA
Andorra          WESTERN EUROPE
...                                              ...
West Bank        NEAR EAST
Western Sahara   NORTHERN AFRICA
Yemen            NEAR EAST
Zambia           SUB-SAHARAN AFRICA
Zimbabwe         SUB-SAHARAN AFRICA

[227 rows x 1 columns]

In [87]:
df2.index

Index(['Afghanistan ', 'Albania ', 'Algeria ', 'American Samoa ', 'Andorra ',
       'Angola ', 'Anguilla ', 'Antigua & Barbuda ', 'Argentina ', 'Armenia ',
       ...
       'Vanuatu ', 'Venezuela ', 'Vietnam ', 'Virgin Islands ',
       'Wallis and Futuna ', 'West Bank ', 'Western Sahara ', 'Yemen ',
       'Zambia ', 'Zimbabwe '],
      dtype='str', name='Country', length=227)

In [88]:
df2.loc['Venezuela ']

Region    LATIN AMER. & CARIB
Name: Venezuela , dtype: str

KeyError: False